version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ps09_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root*
      POSTGRES_DB: DB_project
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ../../mysql:/docker-entrypoint-initdb.d

volumes:
  db_data:
